In [1]:
import numpy as np

In [3]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [4]:
#asociativa
ABC = A.dot(B.dot(C))
ABC

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [6]:
AB_C = A.dot(B).dot(C)
AB_C

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [7]:
#distributiva
D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

In [8]:
D

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

In [9]:
E

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

In [10]:
D==E

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [12]:
#conmutativa
F = B.dot(C)
G = C.dot(B)

In [13]:
F==G

array([[False, False],
       [False, False]])

In [14]:
F

array([[15,  7],
       [10,  4]])

In [15]:
G

array([[ 5, 10],
       [ 8, 14]])

Pero la multiplicacion de vectores si es conmutativa

In [16]:
v1 = np.array([2,7])
v2 = np.array([3,5])

In [17]:
v1_tv2 = v1.T.dot(v2)

In [18]:
v2_tv2 = v2.T.dot(v1)

In [19]:
v1_tv2

41

In [20]:
v2_tv2

41