In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

In [3]:
# 3x + y = 1
# 2x + y = 1

In [4]:
A = np.array([[3,1],[2,1]])
print(A)

[[3 1]
 [2 1]]


In [5]:
b = np.array([[1],[1]])
print(b)

[[1]
 [1]]


In [7]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1. -1.]
 [-2.  3.]]


In [8]:
x = A_inv.dot(b)
print(x)

[[0.]
 [1.]]
