In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)
matriz

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [4]:
matriz[:4, :3] #diagonal pero no cuadrada

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3],
       [0, 0, 0]])

In [5]:
matriz[:3, :4] #diagonal pero no cuadrada

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [6]:
#veamos que la matriz diagonal no es combinacion lineal sino PONDERACIÓN
A = np.diag([2,3,4,5])
vector = np.array([1,1,1,1])

vector

array([1, 1, 1, 1])

In [8]:
print(A.dot(vector.T))

[2 3 4 5]


In [9]:
A_inv = np.diag([1/2,1/3,1/4,1/5])
A_inv

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [10]:
A.dot(A_inv)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.linalg.inv(A)

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [12]:
#SIMETRICAS
sim = np.array([[1,2,3],
                [2,-1,7],
                [3,7,11]])
sim

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])

In [13]:
sim.T

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])

In [14]:
sim == sim.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])