In [1]:
import numpy as np

In [4]:
matriz = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]])
matriz

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
matriz[:,0].dot(matriz[:,1])

0

In [6]:
matriz[:,0].dot(matriz[:,2])

0

In [7]:
matriz[:,1].dot(matriz[:,2])

0

In [8]:
np.linalg.norm(matriz[:,0])

1.0

In [10]:
np.linalg.norm(matriz[:,1])

1.0

In [11]:
np.linalg.norm(matriz[:,2])

1.0

In [12]:
matriz[0,:].dot(matriz[1,:])

0

In [13]:
matriz[0,:].dot(matriz[2,:])

0

In [14]:
matriz[1,:].dot(matriz[2,:])

0

In [15]:
np.linalg.norm(matriz[0,:])

1.0

In [16]:
np.linalg.norm(matriz[1,:])

1.0

In [17]:
np.linalg.norm(matriz[2,:])

1.0

In [18]:
A = np.array([[np.cos(100), -np.sin(100)],
              [np.sin(100), np.cos(100)]])
A

array([[ 0.86231887,  0.50636564],
       [-0.50636564,  0.86231887]])

In [20]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [21]:
print(A[:,0].dot(A[:,1]))
print(A[0,:].dot(A[1,:]))

0.0
0.0


In [22]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


In [23]:
#cuidado con eso bob esponja... debería ser cero

In [26]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.86231887, -0.50636564],
       [ 0.50636564,  0.86231887]])

In [27]:
A_t

array([[ 0.86231887, -0.50636564],
       [ 0.50636564,  0.86231887]])

In [28]:
1/A_t.dot(A)

array([[ 1.00000000e+00, -1.25980837e+17],
       [-1.25980837e+17,  1.00000000e+00]])