In [1]:
import numpy as np

In [3]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])

In [4]:
matriz_t = matriz.T
matriz_t

array([[1, 3, 5],
       [2, 4, 6]])

In [6]:
matriz.shape

(3, 2)

In [7]:
matriz_t.shape

(2, 3)

In [8]:
tensor_t = tensor.T

In [9]:
tensor_t

array([[[ 1, 11, 21],
        [ 4, 14, 24],
        [ 7, 17, 27]],

       [[ 2, 12, 22],
        [ 5, 15, 25],
        [ 8, 18, 28]],

       [[ 3, 13, 23],
        [ 6, 16, 26],
        [ 9, 19, 29]]])

In [11]:
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [12]:
tensor.shape

(3, 3, 3)

In [14]:
tensor_t.shape

(3, 3, 3)