In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [4]:
A = matriz.T + vector
A

array([[2, 5, 8],
       [3, 6, 9]])

In [5]:
matriz.T

array([[1, 3, 5],
       [2, 4, 6]])

In [6]:
vector

array([1, 2, 3])

Cuando hacemos una suma de una matriz con un escalar internamente se está haciendo broadcasting

In [7]:
D = matriz + 50

In [8]:
D

array([[51, 52],
       [53, 54],
       [55, 56]])

In [9]:
matriz + np.array([[50],[50],[50]])

array([[51, 52],
       [53, 54],
       [55, 56]])