In [1]:
import numpy as np

In [3]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [4]:
A = matriz * vector

In [5]:
A

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

In [6]:
B = matriz.dot(vector)

In [7]:
B

array([ 8, 18, 28])

In [8]:
matriz @ vector

array([ 8, 18, 28])

In [9]:
vector@matriz

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)